version: 2.1
orbs:
   node: circleci/node@3.0.0
workflows:
   node-tests:
      jobs:
         - node/test
 steps:
      - checkout
      - run: 
          name: "echo an env var that is part of my project"
          command: |
            echo $MONGO_URI # this env var must be set within the project